//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace map
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=Contexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Reserva> ReservaSet { get; set; }
        public virtual DbSet<Documento> DocumentoSet { get; set; }
        public virtual DbSet<Ejemplar> EjemplarSet { get; set; }
        public virtual DbSet<Categoria> CategoriaSet { get; set; }
        public virtual DbSet<Detalle> DetalleSet { get; set; }
        public virtual DbSet<Prestamo> PrestamoSet { get; set; }
        public virtual DbSet<Multa> MultaSet { get; set; }
        public virtual DbSet<Autor> AutorSet { get; set; }
        public virtual DbSet<Autoria> AutoriaSet { get; set; }
    }
}
